import type { PortfolioItem, Testimonial } from "@/types";

// WhatsApp number (international format, no "+" or leading 0) used for the
// "Continue on WhatsApp" follow-up links on the Quote and Order confirmation
// screens. Sourced from the number shown on the Contact page.
export const WHATSAPP_NUMBER = "2347034986390";

export const SERVICES = [
  {
    id: "business-cards",
    name: "Business Cards",
    icon: "CreditCard",
    description: "Premium business cards with matte, gloss, or spot UV finishes that make a lasting first impression.",
    startingPrice: "₦10,000",
    category: "print",
  },
  {
    id: "banners",
    name: "Banners & Flex",
    icon: "Layout",
    description: "Large-format banners, roll-ups, and flex prints for events, trade shows, and outdoor advertising.",
    startingPrice: "₦5,000",
    category: "signage",
  },
  {
    id: "merchandise",
    name: "Branded Merchandise",
    icon: "Gift",
    description: "Custom-branded mugs, pens, notebooks, bags, and promotional items that keep your brand top of mind.",
    startingPrice: "₦5,000",
    category: "merchandise",
  },
  {
    id: "packaging",
    name: "Packaging",
    icon: "Package",
    description: "Custom boxes, bags, and packaging solutions that tell your brand story from the outside in.",
    startingPrice: "₦15,000",
    category: "print",
  },
  {
    id: "signage",
    name: "Signage",
    icon: "MapPin",
    description: "Indoor and outdoor signage including 3D letters, acrylic boards, LED signs, and wayfinding systems.",
    startingPrice: "₦25,000",
    category: "signage",
  },
  {
    id: "apparel",
    name: "Apparel Printing",
    icon: "Shirt",
    description: "Custom T-shirts, polo shirts, hoodies, and uniforms with screen printing or embroidery.",
    startingPrice: "₦15,000",
    category: "apparel",
  },
  {
    id: "logo-design",
    name: "Logo & Brand Design",
    icon: "Palette",
    description: "Full brand identity packages — logo, color palette, typography, and brand guidelines.",
    startingPrice: "₦45,000",
    category: "branding",
  },
  {
    id: "flyers",
    name: "Flyers & Brochures",
    icon: "FileText",
    description: "Eye-catching flyers, bi-fold and tri-fold brochures, and catalogues for all your marketing needs.",
    startingPrice: "₦10,000",
    category: "print",
  },
];

export const PORTFOLIO_ITEMS: PortfolioItem[] = [
  {
    id: "p1",
    title: "TechHub Lagos Brand Identity",
    category: "branding",
    description: "Complete brand identity including logo, color system, and brand guidelines for a tech co-working space.",
    imageUrl: "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=800&q=80",
    featured: true,
    createdAt: "2026-08-01",
  },
  {
    id: "p2",
    title: "FoodCo Premium Packaging",
    category: "print",
    description: "Custom packaging design and production for a premium food brand's product line.",
    imageUrl: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80",
    featured: true,
    createdAt: "2026-07-20",
  },
  {
    id: "p3",
    title: "Apex Fitness Apparel Line",
    category: "apparel",
    description: "Screen-printed gym wear collection for a fitness brand — 500+ units delivered.",
    imageUrl: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80",
    featured: true,
    createdAt: "2026-07-15",
  },
  {
    id: "p4",
    title: "Summit Conference Signage",
    category: "signage",
    description: "Full event signage suite including rollups, backdrop banners, and directional signs.",
    imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
    featured: false,
    createdAt: "2026-07-10",
  },
  {
    id: "p5",
    title: "GreenLeaf Branded Merch",
    category: "merchandise",
    description: "Corporate gift set with branded mugs, notebooks, and tote bags for an eco-friendly brand.",
    imageUrl: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80",
    featured: false,
    createdAt: "2026-07-05",
  },
  {
    id: "p6",
    title: "Nova Realty Business Cards",
    category: "print",
    description: "Luxury matte business cards with gold foil accent for a premium real estate company.",
    imageUrl: "https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=800&q=80",
    featured: false,
    createdAt: "2026-06-28",
  },
  {
    id: "p7",
    title: "Kalahari Restaurant Branding",
    category: "branding",
    description: "Full restaurant branding — logo, menu design, signage, and branded packaging.",
    imageUrl: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&q=80",
    featured: true,
    createdAt: "2026-06-20",
  },
  {
    id: "p8",
    title: "CityRun Marathon Shirts",
    category: "apparel",
    description: "2,000 custom printed finisher T-shirts for the annual city marathon event.",
    imageUrl: "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=800&q=80",
    featured: false,
    createdAt: "2026-06-10",
  },
  {
    id: "p9",
    title: "Metro Mall Wayfinding",
    category: "signage",
    description: "Complete wayfinding and directional signage system for a large retail mall.",
    imageUrl: "https://images.unsplash.com/photo-1555529669-e69e7aa0ba9a?w=800&q=80",
    featured: false,
    createdAt: "2026-06-01",
  },
  // ─── Extra placeholder slots ─────────────────────────────────────────
  // Each item below points to a placeholder image in public/portfolio/.
  // Replace the image file (same filename) with your own project photo,
  // and edit the title/description/category directly here — or use the
  // Admin dashboard's Portfolio tab, which now supports editing and
  // image upload for every item, including these.
  {
    id: "p10",
    title: "Your Branding Project",
    category: "branding",
    description: "Add a short description of this project here.",
    imageUrl: "/portfolio/branding-1.svg",
    featured: false,
    createdAt: "2026-08-10",
  },
  {
    id: "p11",
    title: "Your Branding Project",
    category: "branding",
    description: "Add a short description of this project here.",
    imageUrl: "/portfolio/branding-2.svg",
    featured: false,
    createdAt: "2026-08-10",
  },
  {
    id: "p12",
    title: "Your Print Project",
    category: "print",
    description: "Add a short description of this project here.",
    imageUrl: "/portfolio/print-1.svg",
    featured: false,
    createdAt: "2026-08-10",
  },
  {
    id: "p13",
    title: "Your Print Project",
    category: "print",
    description: "Add a short description of this project here.",
    imageUrl: "/portfolio/print-2.svg",
    featured: false,
    createdAt: "2026-08-10",
  },
  {
    id: "p14",
    title: "Your Apparel Project",
    category: "apparel",
    description: "Add a short description of this project here.",
    imageUrl: "/portfolio/apparel-1.svg",
    featured: false,
    createdAt: "2026-08-10",
  },
  {
    id: "p15",
    title: "Your Apparel Project",
    category: "apparel",
    description: "Add a short description of this project here.",
    imageUrl: "/portfolio/apparel-2.svg",
    featured: false,
    createdAt: "2026-08-10",
  },
  {
    id: "p16",
    title: "Your Signage Project",
    category: "signage",
    description: "Add a short description of this project here.",
    imageUrl: "/portfolio/signage-1.svg",
    featured: false,
    createdAt: "2026-08-10",
  },
  {
    id: "p17",
    title: "Your Signage Project",
    category: "signage",
    description: "Add a short description of this project here.",
    imageUrl: "/portfolio/signage-2.svg",
    featured: false,
    createdAt: "2026-08-10",
  },
  {
    id: "p18",
    title: "Your Merchandise Project",
    category: "merchandise",
    description: "Add a short description of this project here.",
    imageUrl: "/portfolio/merchandise-1.svg",
    featured: false,
    createdAt: "2026-08-10",
  },
  {
    id: "p19",
    title: "Your Merchandise Project",
    category: "merchandise",
    description: "Add a short description of this project here.",
    imageUrl: "/portfolio/merchandise-2.svg",
    featured: false,
    createdAt: "2026-08-10",
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "t1",
    name: "Adaeze Okonkwo",
    company: "TechHub Lagos",
    rating: 5,
    message: "Mosdal Branding Solution completely transformed our brand identity. The quality of their work is unmatched — every detail was executed perfectly. Our clients constantly ask about our branded materials!",
    avatarUrl: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?w=150&q=80",
    approved: true,
    createdAt: "2026-08-05",
  },
  {
    id: "t2",
    name: "Emeka Obi",
    company: "Apex Fitness",
    rating: 5,
    message: "Fast turnaround, incredible quality, and the team genuinely cares about getting your brand right. We've ordered apparel three times and it gets better each time.",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&q=80",
    approved: true,
    createdAt: "2026-07-22",
  },
  {
    id: "t3",
    name: "Fatima Al-Hassan",
    company: "GreenLeaf Organics",
    rating: 5,
    message: "The branded merchandise set they created for our corporate event was stunning. Guests were genuinely impressed. Will definitely use Mosdal Branding Solution for all future projects.",
    avatarUrl: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&q=80",
    approved: true,
    createdAt: "2026-07-10",
  },
  {
    id: "t4",
    name: "Chukwudi Nwachukwu",
    company: "Nova Realty",
    rating: 4,
    message: "Our business cards look absolutely premium. The gold foil finish was exactly what I envisioned. Professional service from start to finish.",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&q=80",
    approved: true,
    createdAt: "2026-07-01",
  },
  {
    id: "t5",
    name: "Ngozi Eze",
    company: "Kalahari Restaurant",
    rating: 5,
    message: "From our logo to menus to signage — Mosdal Branding Solution handled everything beautifully. Our restaurant brand looks cohesive and professional. Highly recommend!",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&q=80",
    approved: true,
    createdAt: "2026-06-25",
  },
  {
    id: "t6",
    name: "Tunde Adesanya",
    company: "CityRun Events",
    rating: 5,
    message: "2,000 shirts printed and delivered on time, with zero defects. The quality was excellent and our marathon participants loved them. Mosdal Branding Solution is our go-to for events.",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&q=80",
    approved: true,
    createdAt: "2026-06-15",
  },
];

export const BUDGET_RANGES = [
  "Under ₦20,000",
  "₦20,000 – ₦50,000",
  "₦50,000 – ₦100,000",
  "₦100,000 – ₦250,000",
  "₦250,000 – ₦500,000",
  "Above ₦500,000",
];

// Replace each `logo` path with your own logo file.
// Easiest way: drop your logo images into the `public/brand-logos/` folder
// (any of .svg, .png, .jpg work) and update the path + name below to match.
export const NOTABLE_BRANDS = [
  { name: "Brand 1", logo: "/brand-logos/logo-1.svg" },
  { name: "Brand 2", logo: "/brand-logos/logo-2.svg" },
  { name: "Brand 3", logo: "/brand-logos/logo-3.svg" },
  { name: "Brand 4", logo: "/brand-logos/logo-4.svg" },
  { name: "Brand 5", logo: "/brand-logos/logo-5.svg" },
  { name: "Brand 6", logo: "/brand-logos/logo-6.svg" },
  { name: "Brand 7", logo: "/brand-logos/logo-7.svg" },
  { name: "Brand 8", logo: "/brand-logos/logo-8.svg" },
];
